---
output:
  html_document:                    # Classe de documento.
    toc: true                       # Exibir sum?rio.
    toc_depth: 2                    # Profundidade do sum?rio.
    toc_float:                      # Sum?rio flutuante na borda.
      collapsed: true
      smooth_scroll: true
    number_sections: false           # Se??es numeradas.
    theme: cosmo
    #spacelab
    #default,cerulean,journal,flatly,readable,spacelab,
    #united,cosmo,lumen,paper,sandstone,simplex,yeti
    
    highlight: espresso
    #default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, and textmate
    #css: styles.css                 # Caminho para arquivo CSS.
    fig_width: 7                    # Lagura das figuras.
    fig_height: 6                   # Altura das figuras.
    fig_caption: true               # Exibica??o de legenda.
    fig_align: 'center'
    code_folding: hide              # Esconder/exibir bloco de c?digo.
#    keep_md: true                   # Manter o arquivo md.
    #template: quarterly_report.html # Caminho para o template.  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE,fig.align='center', fig.width=5, fig.height=5)

#--------------------------------------------------------------
setwd("~/msc/4_latencias")
#--------------------------------------------------------------

library(tidyverse)
library(gridExtra)
library(ggpubr)

source('funcoes.R')

#--------------------------------------------------------------

# DADOS
#--------------------------------------------------------------

dados <- read.csv2('tissei.csv', header = T, sep = ',')

str(dados)

names(dados) <- c('n', 'inst', 'lock', 'set_rex', 'segment',
                  'mem_xchg', 'p0156', 'p06', 'p23', 'p237', 
                  'p4', 'p1', 'p15', 'p015', 'p5', 'p0', 
                  'p05', 'p01', 'p6', 'min_lat', 'max_lat')

```

---

<center>
<font size="6"> 
<p align=”center”> <b> Considerações finais </b> </center>
</font>
</center>

---

# Conclusões

 - As tabelas de frequência mostram baixíssimas frequências das indicadoras igual a 1 para set_rex e mem_xchg, portanto é difícil avaliar diferença entre os níveis.

 - Para lock a frequência não é tão baixa mas ainda sim o desbalenceamento entre os níveis é alto, portanto, cuidado com as conclusões.

 - As portas 0156, 06, 23, 237, 4 e 1 possuem frequência mais alta em diferentes valores, com elas é mais fácil de avaliar o que acontece com as latências.

 - As demais portas predominantemente não foram usadas, mais de 90% de vezes assumem o valor 0.

 - A massa de latências está entre 0 e 20 para a mínima e 0 e 40 para a máxima, valores fora desses intervalos são poucos e extremos.

 - Em média, as portas 0156, 06 e 23 são mais usadas que as demais.

 - Em média, a latência máxima é o dobro da mínima

 - Marginalmente, lock = 1 está associado a latências mais altas.

 - As portas associadas a maiores latências são: 0156, 23 e 4.

---

# Possível continuação

 - Refazer as tabelas e gráficos considerando os subsets.

 - Considerar outros subsets como p0156<5, p06<7, p23<3, p237, p4<3, p1<4, descartar as demais.

 - Gerar um dataset para análise em massa considerando os filtros acima, e um para análise 'manual' por um analista.


---

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>