---
output:
  html_document:                    # Classe de documento.
    toc: true                       # Exibir sum?rio.
    toc_depth: 2                    # Profundidade do sum?rio.
    toc_float:                      # Sum?rio flutuante na borda.
      collapsed: true
      smooth_scroll: true
    number_sections: false           # Se??es numeradas.
    theme: cosmo
    #spacelab
    #default,cerulean,journal,flatly,readable,spacelab,
    #united,cosmo,lumen,paper,sandstone,simplex,yeti
    
    highlight: espresso
    #default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, and textmate
    #css: styles.css                 # Caminho para arquivo CSS.
    fig_width: 7                    # Lagura das figuras.
    fig_height: 6                   # Altura das figuras.
    fig_caption: true               # Exibica??o de legenda.
    fig_align: 'center'
    code_folding: hide              # Esconder/exibir bloco de c?digo.
#    keep_md: true                   # Manter o arquivo md.
    #template: quarterly_report.html # Caminho para o template.  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE,fig.align='center', fig.width=5, fig.height=5)

#--------------------------------------------------------------
setwd("~/msc/4_latencias")
#--------------------------------------------------------------

library(tidyverse)
library(gridExtra)
library(ggpubr)

source('funcoes.R')

#--------------------------------------------------------------

# DADOS
#--------------------------------------------------------------

dados <- read.csv2('tissei.csv', header = T, sep = ',')

str(dados)

names(dados) <- c('n', 'inst', 'lock', 'set_rex', 'segment',
                  'mem_xchg', 'p0156', 'p06', 'p23', 'p237', 
                  'p4', 'p1', 'p15', 'p015', 'p5', 'p0', 
                  'p05', 'p01', 'p6', 'min_lat', 'max_lat')

```

---

<center>
<font size="6"> 
<p align=”center”> <b> Medidas de posição e dispersão </b> </center>
</font>
</center>

---

# Medidas de posição

<center>
```{r,echo=FALSE}
# Medidas de posição
m_p0156 <- posic(dados$p0156)
m_p06 <- posic(dados$p06)     
m_p23 <- posic(dados$p23)      
m_p237 <- posic(dados$p237)     
m_p4 <- posic(dados$p4)       
m_p1 <- posic(dados$p1)      
m_p15 <- posic(dados$p15)      
m_p015 <- posic(dados$p015)     
m_p5 <- posic(dados$p5)       
m_p0 <- posic(dados$p0)      
m_p05 <- posic(dados$p05)      
m_p01 <- posic(dados$p01)      
m_p6 <- posic(dados$p6)
m_min_lat <- posic(dados$min_lat)
m_max_lat <- posic(dados$max_lat)

m1 <- rbind(m_p0156, m_p06, m_p23, m_p237,
            m_p4, m_p1, m_p15, m_p015, m_p5,
            m_p0, m_p05, m_p01, m_p6, m_min_lat,
            m_max_lat)

row.names(m1) <- c("p0156", "p06", "p23", "p237",
                   "p4", "p1", "p15", "p015", "p5",
                   "p0", "p05", "p01", "p6", "min_lat",
                   "max_lat")

pander::pander(m1)

```

</center>

---

# Medidas de dispersão

<center>
```{r,echo=FALSE}
# Medidas de dispersão
d_p0156 <- disp(dados$p0156)    
d_p06 <- disp(dados$p06)     
d_p23 <- disp(dados$p23)      
d_p237 <- disp(dados$p237)     
d_p4 <- disp(dados$p4)       
d_p1 <- disp(dados$p1)      
d_p15 <- disp(dados$p15)      
d_p015 <- disp(dados$p015)     
d_p5 <- disp(dados$p5)       
d_p0 <- disp(dados$p0)      
d_p05 <- disp(dados$p05)      
d_p01 <- disp(dados$p01)      
d_p6 <- disp(dados$p6)
d_min_lat <- disp(dados$min_lat)
d_max_lat <- disp(dados$max_lat)

d1 <- rbind(d_p0156, d_p06, d_p23, d_p237,
            d_p4, d_p1, d_p15, d_p015, d_p5,
            d_p0, d_p05, d_p01, d_p6, d_min_lat,
            d_max_lat)

row.names(d1) <- c("p0156", "p06", "p23", "p237",
                   "p4", "p1", "p15", "p015", "p5",
                   "p0", "p05", "p01", "p6", "min_lat",
                   "max_lat")



pander::pander(d1)

```

</center>

---

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>