---
output:
  html_document:                    # Classe de documento.
    toc: true                       # Exibir sum?rio.
    toc_depth: 2                    # Profundidade do sum?rio.
    toc_float:                      # Sum?rio flutuante na borda.
      collapsed: true
      smooth_scroll: true
    number_sections: false           # Se??es numeradas.
    theme: cosmo
    #spacelab
    #default,cerulean,journal,flatly,readable,spacelab,
    #united,cosmo,lumen,paper,sandstone,simplex,yeti
    
    highlight: espresso
    #default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, and textmate
    #css: styles.css                 # Caminho para arquivo CSS.
    fig_width: 7                    # Lagura das figuras.
    fig_height: 6                   # Altura das figuras.
    fig_caption: true               # Exibica??o de legenda.
    fig_align: 'center'
    code_folding: hide              # Esconder/exibir bloco de c?digo.
#    keep_md: true                   # Manter o arquivo md.
    #template: quarterly_report.html # Caminho para o template.  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE,fig.align='center', fig.width=5, fig.height=5)

#--------------------------------------------------------------
setwd("~/msc/4_latencias")
#--------------------------------------------------------------

library(tidyverse)
library(gridExtra)
library(ggpubr)

source('funcoes.R')

#--------------------------------------------------------------

# DADOS
#--------------------------------------------------------------

dados <- read.csv2('tissei.csv', header = T, sep = ',')

str(dados)

names(dados) <- c('n', 'inst', 'lock', 'set_rex', 'segment',
                  'mem_xchg', 'p0156', 'p06', 'p23', 'p237', 
                  'p4', 'p1', 'p15', 'p015', 'p5', 'p0', 
                  'p05', 'p01', 'p6', 'min_lat', 'max_lat')


```

---

<center>
<font size="6"> 
<p align=”center”> <b> Tabelas de frequência </b> </center>
</font>
</center>

---

# Variáveis indicadoras {.tabset .tabset-fade}

## Binárias

<center>
```{r, echo=FALSE}
ind <- data.frame(Variável = c('lock', 'set_rex', 
                        'mem_xchg'),
           Frequencia_0 = c(table(dados$lock)[1],
                            table(dados$set_rex)[1],
                            table(dados$mem_xchg)[1]),
           Frequencia_1 = c(table(dados$lock)[2],
                            table(dados$set_rex)[2],
                            table(dados$mem_xchg)[2]))

pander::pander(ind)

```
</center>

---

## Segment

<center>
```{r, echo=FALSE}
seg <- factor(dados$segment, levels = 0:6)
seg <- as.data.frame(table(seg))
names(seg) <- c('Níveis', 'Frequência')
seg$Freq_relativa <- round(prop.table(seg$Frequência),3)

pander::pander(seg)

```
</center>

---

## Vetor

<center>
```{r, echo=FALSE}
# Unindo as indicadoras num mesmo vetor
ind <- rep(NA, nrow(dados))
ind <- ifelse(dados$lock == 1, 'lock', ind)
ind <- ifelse(dados$set_rex == 1, 'set_rex', ind)
ind <- ifelse(dados$mem_xchg == 1, 'mem_xchg', ind)
ind <- ifelse(dados$segment %in% 1:6, 'segment', ind)
ind <- ifelse(is.na(ind) == T, 'outro', ind)

ind <- factor(ind, levels = c("outro","lock","segment","set_rex", "mem_xchg"))

ind <- as.data.frame(table(ind))
names(ind) <- c('Variável', 'Frequência')
ind$Freq_relativa <- round(prop.table(ind$Frequência),3)
                     
pander::pander(ind)

```
</center>

---

# Portas {.tabset .tabset-fade}

```{r, echo=FALSE}

t_p0156 <- tb_freq(dados$p0156)
t_p06 <- tb_freq(dados$p06)
t_p23 <- tb_freq(dados$p23)
t_p237 <- tb_freq(dados$p237)
t_p4 <- tb_freq(dados$p4)
t_p1 <- tb_freq(dados$p1)
t_p15 <- tb_freq(dados$p15)
t_p015 <- tb_freq(dados$p015)
t_p5 <- tb_freq(dados$p5)
t_p0 <- tb_freq(dados$p0)
t_p05 <- tb_freq(dados$p05)
t_p01 <- tb_freq(dados$p01)
t_p6 <- tb_freq(dados$p6)

```

---

## p0156

<center>
```{r, echo=FALSE}
pander::pander(t_p0156)
```
</center>

---

## p06

<center>
```{r, echo=FALSE}
pander::pander(t_p06)
```
</center>

---

## p23

<center>
```{r, echo=FALSE}
pander::pander(t_p23)
```
</center>

---

## p237

<center>
```{r, echo=FALSE}
pander::pander(t_p237)
```
</center>

---

## p4

<center>
```{r, echo=FALSE}
pander::pander(t_p4)
```
</center>

---

## p1

<center>
```{r, echo=FALSE}
pander::pander(t_p1)
```
</center>

---

## p15

<center>
```{r, echo=FALSE}
pander::pander(t_p15)
```
</center>

---

## p015

<center>
```{r, echo=FALSE}
pander::pander(t_p015)
```
</center>

---

## p5

<center>
```{r, echo=FALSE}
pander::pander(t_p5)
```
</center>

---

## p0

<center>
```{r, echo=FALSE}
pander::pander(t_p0)
```
</center>

---

## p05

<center>
```{r, echo=FALSE}
pander::pander(t_p05)
```
</center>

---

## p01

<center>
```{r, echo=FALSE}
pander::pander(t_p01)
```
</center>

---

## p6

<center>
```{r, echo=FALSE}
pander::pander(t_p6)
```
</center>

---

# Latências 

---

## Mínima {.tabset .tabset-fade}

### Tabela 1

<center>
```{r, echo=FALSE}

h <- hist(dados$min_lat, plot = FALSE)
breaks <- h$breaks
Classes <- cut(dados$min_lat, breaks = breaks, 
               include.lowest = TRUE, right = TRUE)
tabela1_min <- as.data.frame(table(Classes))
tabela1_min$Freq_relativa <- round(prop.table(tabela1_min$Freq),3)

pander::pander(tabela1_min)

```
</center>

---

### Tabela 2

<center>
```{r, echo=FALSE}
breaks2 <- c(seq(0,35,5), seq(40, 80,20), seq(100, max(dados$max_lat), max(dados$max_lat)-100))
Classes <- cut(dados$min_lat, breaks = breaks2, 
               include.lowest = TRUE, right = TRUE)
tabela2_min <- as.data.frame(table(Classes))
tabela2_min$Freq_relativa <- round(prop.table(tabela2_min$Freq),3)

pander::pander(tabela2_min)

```
</center>

---

## Máxima {.tabset .tabset-fade}

### Tabela 1

<center>
```{r,echo=FALSE}
h <- hist(dados$max_lat, plot = FALSE)
breaks <- h$breaks
Classes <- cut(dados$max_lat, breaks = breaks, 
               include.lowest = TRUE, right = TRUE)
tabela1_max <- as.data.frame(table(Classes))
tabela1_max$Freq_relativa <- round(prop.table(tabela1_max$Freq),3)

pander::pander(tabela1_max)

```

</center>
---

### Tabela 2

<center>
```{r,echo=FALSE}
breaks2 <- c(seq(0,35,5), seq(40, 80,20), seq(100, max(dados$max_lat), max(dados$max_lat)-100))
Classes <- cut(dados$max_lat, breaks = breaks2, 
               include.lowest = TRUE, right = TRUE)

tabela2_max <- as.data.frame(table(Classes))
tabela2_max$Freq_relativa <- round(prop.table(tabela2_max$Freq),3)

pander::pander(tabela2_max)

```
</center>

---

<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>